---
title: "Processo"
subtitle: "metalm"
author: "philippe.brunier@cogne.com"
version: 1.0 
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    css: ./custom.css
    df_print: paged
    gallery: no
    highlight: default
    html_document: null
    lightbox: yes
    number_sections: yes
    self_contained: yes
    thumbnails: no
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      fig.height = 7,
                      fig.width = 10,
                      collapse = TRUE,
                      cols.print=20)
rm(list = ls(all.names = TRUE))



```

# Processo

Report delle prove di laborabilità. 

Il report contiene il riassunto delle caraterizzazioni in termini di lavorabilità, contentente i seguenti output:

+ dati metallografici

  + micropurezza - DIN 50602
  
  + micropurezza - SEP 1571
  
  + micropurezza - ASTM E45
  
  + dimensione grano - ASTM E112

+ chimiche di prodotto  

  + carbonio e zolfo - ASTM E1019
  
  + azoto ed ossigeno - ASTM E1019
  
  + spettrometria ad emissione ottica per il resto dell'analisi - ASTM E1086

+ prove meccaniche

  + prove a trazione
  
  + prove di durezza (Brinnel) - ASTM E10  

+ prove di lavorabilità


I dati di lavorabilità (forze, usura) sono frutto di misure in laboratorio effettuate con le seguenti specifiche:

+ macchina: OKUMA LB2000EX-II
+ lubrificante: BLASER BLASOCUT2000 universal
+ utensile: SANDVICK DNMG 150608–MR 2035
+ dinamometro: KISTLER 9129AA
+ amplificatore: KISTLER 5167A81DK