---
title: "Comparativa materiali"
subtitle: "metalm"
author: "pbrunier@cogne.com"
version: 1.0 
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    css: ./custom.css
    df_print: paged
    gallery: no
    highlight: default
    html_document: null
    lightbox: yes
    number_sections: yes
    self_contained: yes
    thumbnails: no
runtime: shiny
editor_options:
  chunk_output_type: console

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      fig.height = 7,
                      fig.width = 10,
                      collapse = TRUE,
                      cols.print=20)
rm(list = ls(all.names = TRUE))
require(dplyr)
require(rlang)
require(kableExtra)
require(readr)
require(ggplot2)
require(reticulate)
source('~/dev/metalm/R/function.R')
```

```{python read_pickle}
import pandas as pd

df = pd.read_pickle('/data/metalm/pickle/dbmm.pkl')

```

```{r shiny_part}

dfr <- py$df

lista_materiali <- unique(dfr$materiale)

inputPanel(
         selectInput("marca_1", label = 'scegli la marca 1', 
                      choices = lista_materiali, selected = length(lista_materiali)),

        selectInput("marca_2", label = 'scegli la marca 2', 
                      choices = lista_materiali, selected = length(lista_materiali),multiple = TRUE)
)

```

```{r prova_stampa_materiali}

tempo_usura_materiali <- dfr %>% select(materiale, tempo_usura)

tempo_usura_materiali <- tempo_usura_materiali %>% arrange(materiale)

tempo_usura_LO <- subset(tempo_usura_materiali, materiale == 'F304LO')
tempo_usura_L1 <- subset(tempo_usura_materiali, materiale == 'F304L1')
tempo_usura_LX <- subset(tempo_usura_materiali, materiale == 'F304LX')
tempo_usura_LH <- subset(tempo_usura_materiali, materiale == 'F304LH')

materiali <- renderPrint({
  print(
    ifelse(input$marca_1 == 'F304LO',
              mean(tempo_usura_LO$tempo_usura),
               ifelse(input$marca_1 == 'F304L1',
                       mean(tempo_usura_L1$tempo_usura),
                        ifelse(input$marca_1 == 'F304LX',
                                 mean(tempo_usura_LX$tempo_usura),
                                 ifelse(input$marca_1 == 'F304LH',
                                        tempo_usura_LH$tempo_usura,
                                        imput$marca_1
              )))));
  ifelse(input$marca_2 == 'F304LO',
              mean(tempo_usura_LO$tempo_usura),
               ifelse(input$marca_2 == 'F304L1',
                       mean(tempo_usura_L1$tempo_usura),
                        ifelse(input$marca_2 == 'F304LX',
                                 mean(tempo_usura_LX$tempo_usura),
                                 ifelse(input$marca_2 == 'F304LH',
                                        tempo_usura_LH$tempo_usura,
                                        imput$marca_2
              ))));
  })

materiali

```


